artifactory:
  build: ./artifactory
  ports:
    - "18081:8080"
  volumes:
    - /d/docker/data/artifactory/data:/artifactory/data:rw
    - /d/docker/data/artifactory/logs:/artifactory/logs:rw
    - /d/docker/data/artifactory/backup:/artifactory/backup:rw

jenkins:
  build: ./jenkins
  ports:
    - "18080:8080"
  links:
    - artifactory:artifactory
    - gitlab:gitlab
    - sonar:sonar
    - selhub:hub
  volumes:
    - /d/docker/data/jenkins:/var/jenkins_home:rw

sonar:
  build: ./sonar
  ports:
   - "19000:9000"
  environment:
   - SONARQUBE_JDBC_URL=jdbc:h2://192.168.99.100/sonar
   - SONARQUBE_JDBC_USERNAME=sonar
   - SONARQUBE_JDBC_PASSWORD=sonar
  volumes:
    - /d/docker/data/sonarqube/data:/opt/sonarqube/data:rw
    - /d/docker/data/sonarqube/logs:/opt/sonarqube/logs:rw
    - /d/docker/data/sonarqube/extensions:/opt/sonarqube/extensions:rw

selhub:
  image: selenium/hub
  ports:
    - 4444:4444

nodefirefox:
  image: selenium/node-firefox-debug
  ports:
    - 5900
  links:
    - selhub:hub

nodechrome:
  image: selenium/node-chrome-debug
  ports:
    - 5900
  links:
    - selhub:hub

postgresql:
  build: ./postgresql
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
  volumes:
    - /d/docker/data/postgresql/run:/run/postgresql:rw
    - /d/docker/data/postgresql/data:/var/lib/postgresql:rw
    - /d/docker/data/postgresql/log:/var/log/postgresql:rw
    
gitlab:
  build: ./gitlab
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - TZ=Europe/Amsterdam
    - GITLAB_TIMEZONE=Amsterdam

    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string

    - GITLAB_HOST=192.168.99.100
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=meskena@gmail.com
    - GITLAB_EMAIL_REPLY_TO=cdtoolstack@gmail.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=meskena@gmail.com

    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false
  volumes:
    - /d/docker/data/gitlab/data:/home/git/data:rw
    - /d/docker/data/gitlab/log:/var/log/gitlab:rw
    
redis:
  build: ./redis
  volumes:
    - /d/docker/data/redis/data:/var/lib/redis:rw
    - /d/docker/data/redis/log:/var/log/redis:rw