artifactory:
  build: ./artifactory
  ports:
    - "18081:8081"
  volumes:
    - ./data_volume/artifactory/data:/artifactory/data:rw
    - ./data_volume/artifactory/logs:/artifactory/logs:rw
    - ./data_volume/artifactory/backup:/artifactory/backup:rw

jenkins:
  build: ./jenkins
  ports:
    - "18080:8080"
  links:
    - artifactory:artifactory
    - gitlab:gitlab
    - sonar:sonar
    - selhub:hub
  volumes:
    - ./data_volume/jenkins:/var/jenkins_home:rw

sonar:
  build: ./sonar
  ports:
   - "19000:9000"
   - "5432:5432"
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://192.168.99.100:5432/sonar
  volumes:
    - ./data_volume/sonarqube/data:/opt/sonarqube/data:rw
    - ./data_volume/sonarqube/logs:/opt/sonarqube/logs:rw
    - ./data_volume/sonarqube/extensions:/opt/sonarqube/extensions:rw
    
db:
  image: postgres
  net: container:sonar
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar

selhub:
  image: selenium/hub
  ports:
    - 4444:4444

nodeff:
  image: selenium/node-firefox-debug
  ports:
    - 5900
  links:
    - selhub:hub

nodechrome:
  image: selenium/node-chrome-debug
  ports:
    - 5900
  links:
    - selhub:hub

postgresql:
  image: sameersbn/postgresql
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
  volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql
    
gitlab:
  image: sameersbn/gitlab
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - TZ=Europe/Amsterdam
    - GITLAB_TIMEZONE=Amsterdam

    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string

    - GITLAB_HOST=192.168.99.100
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=meskena@gmail.com
    - GITLAB_EMAIL_REPLY_TO=cdtoolstack@gmail.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=meskena@gmail.com

    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
    
redis:
  image: sameersbn/redis
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis
